# Generated by Django 5.0 on 2023-12-14 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userconfirmation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userconfirmation",
            options={
                "verbose_name": "User confirmation",
                "verbose_name_plural": "Users confirmation",
            },
        ),
    ]
